[package]
name = "wscreensaver-bridge"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
zbus = { version = "4.3.1", default-features = false, features = ["tokio"] }
zbus_macros = "4.3.1"
log = "0.4.20"
pretty_env_logger = "0.5.0"
fastrand = "2.1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
wayland-client = "0.31.3"
wayland-protocols = { version = "0.32.1", features = ["unstable", "client"] }
ctrlc = { version = "3.4", features = ["termination"] }
atomic-wait = "1.1.0"
