[package]
name = "wscreensaver-bridge"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = { version = "0.9.7", features = ["vendored"] }
dbus-crossroads = "0.5.2"
dbus-tokio = "0.7.6"
futures = "0.3.30"
log = "0.4.20"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
wayland-client = "0.31.3"
wayland-protocols = { version = "0.32.1", features = ["unstable", "client"] }
